"""implementando as funções do usuário

Revision ID: 258234cb2a20
Revises: 39ad309fd262
Create Date: 2024-06-17 08:08:05.564086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258234cb2a20'
down_revision: Union[str, None] = '39ad309fd262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('funcoes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'funcoes')
    # ### end Alembic commands ###
