"""update tables

Revision ID: ba4802191eb5
Revises: 76751760fef5
Create Date: 2024-06-15 14:39:30.567891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4802191eb5'
down_revision: Union[str, None] = '76751760fef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_index('ix_products_description', table_name='products')
    op.drop_index('ix_products_section', table_name='products')
    op.drop_column('products', 'available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_products_section', 'products', ['section'], unique=False)
    op.create_index('ix_products_description', 'products', ['description'], unique=False)
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=True)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    # ### end Alembic commands ###
